# Generated by Django 3.2 on 2021-05-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='milage',
            new_name='mileage',
        ),
    ]
