# Generated by Django 3.2 on 2021-05-08 09:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='food',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must greater than two characters')]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must greater than two characters')]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
