# Generated by Django 3.2 on 2021-05-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20210508_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='food',
            new_name='foods',
        ),
    ]
